#server
server:
  session:
    timeout: 3600 #秒
  context-path: /

#spring
spring:
  profiles:
    active: dev
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect
  #aop
  aop:
    auto: true # Add @EnableAspectJAutoProxy
    proxy-target-class: false
  http:
    #编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    #MultipartResolver
    multipart:
      enabled: false #关闭自带multipartResolver,否则commonsMultipartResolver解析会得不到数据

#mybatis
#mybatis:
#  mapper-locations: #classpath:mapper/**/*.xml
#  type-aliases-package: #com.xwbing.domain.entity
#  config-location: # classpath:mybatisConfig.xml


pagehelper:
  helper-dialect: mysql
#log
logging:
  config: classpath:log4j2.xml

#阿里云配置
aliYunLog:
  accessId:
  accessKey:
  endpoint: cn-shenzhen.log.aliyuncs.com
  project: boot-api
  topic: boot_moddule

