server:
  port: 8080

spring:
  mail:
    host: smtp.163.com
    username: xwb1ng@163.com
    password: xwbing000111 #邮箱设置里获取的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true #授权
          starttls:
            enable: true
            required: true
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000 #毫秒
    publisher-confirms: true #支持发布确认（确认消息是否发送到交换器）
    publisher-returns: true #支持发布返回（确认消息没有存入到相应的队列）
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual #消息接收手动ack确认

#xxl-job
xxl:
  job:
    admin:
      #admin address list, such as "http://address" or "http://address01,http://address02"
      addresses: http://127.0.0.1:7777/xxl-job-admin
    #xxl-job executor address
    executor:
      appname: boot-web
      ip:
      port: 9990
      logpath: logs/jobhandler
      logretentiondays: -1
    accessToken:

redis:
  host: 127.0.0.1
  port: 6379
  password: xwbing
  timeout: 10000
  maxTotal: 8
  maxIdle: 8
  minIdle: 0
  prefix: bootWeb-
  enabled: true
#阿里云配置
aliYunLog:
  project: boot-api
  logStore: test_boot
