server:
  port: 8081

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000 #毫秒
    publisher-confirms: true #支持发布确认（确认消息是否发送到交换器）
    publisher-returns: true #支持发布返回（确认消息没有存入到相应的队列）
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual #消息接收手动ack确认

boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    maxTotal: 100
    maxIdle: 10
    minIdle: 0
  aliYun:
    log:
      log-store: prod_lease
    ding-talk:
      web-hook: https://oapi.dingtalk.com/robot/send?access_token=3895a756e1e59a751fdccabed9f019def6d23acce3ee9f3e6c70b4d96744ea91
      secret: SECf84bb8feb4f414fd0a298f2258bf1bfa512ddf79086033f6ce5739a5c7614ff9

